spring:
  application:
    name: oasis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miro?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PWD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: "((a, b) => a.get('operationId').localeCompare(b.get('operationId')))"

oauth:
  kakao:
    client-id: 0283c27599aef19ed65bcde74a5cb98b
    client-secret: iW13MsbFX7RyLS9MCXf9tXHTBbxjKjQ5
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: http://localhost:8080/oauth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
